title: NLP Reading Group, Dhaka
description: >-
  A Dhaka based Reading Group for Natural Language Processing and Deep Learning Research
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nlp-reading-group-dhaka.github.io/" # the base hostname & protocol for your site, e.g. https://example.com

theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: NLP & ML
      # img: ''
      url:
    links:
      - name: Program
        relative_url: /program/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: Location
        relative_url: /location/
      - name: Previous Editions
        menu:
          - name: 2022 (current)
            disabled: true
          - name: 2018 (NCSU)
            absolute_url: http://neutron.physics.ncsu.edu/NeutronSummerSchool/
          - name: 2015 (UTK)
            absolute_url: http://www.phys.utk.edu/neutron-summer-school/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/
      - name: How to get there
        relative_url: /location/
      - name: Registration
        absolute_url: https://forms.gle/F1VVMUGfqhZxHwALA

  # Information boxes
  info_bars:
    - title: Registration open for Fall 2021 reading sessions!
      color: primary
      main_only: true
      text: |
        The fall course will build on top of summer readings. We plan to host more advanced research discussions in natural
        language processing and its subsequent fields. We have now prepared a course including 15 nlp papers,
        4 hands-on tutorials, and 2 lightning sessions.

        ---

        Register here - [https://forms.gle/F1VVMUGfqhZxHwALA](https://forms.gle/F1VVMUGfqhZxHwALA)
    - text: We usually meet each Sunday Bangladesh time 8 pm.
      color: warning
      pages_only: true

  # Live indications
  live:
    date: 15.07.2022
    timezone: GMT-5
    time_stop: 240      # in minutes
    streaming:
      time_pause:   60  # in minutes
      time_prepend:  5  # in minutes
      time_extend:   5  # in minutes
    demo: false

  talks:
    # Talk categories
    main_categories:
      - name: Sentence Classification
        color: info
      - name: Sequence Labeling
        color: success
      - name: Seq2seq and Attention
        color: success
      - name: Pre-trained Language Models & Fine-tuning
        color: success
      - name: Question answering, Summarization
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # URL of location / room overview page
    url: '/location'

    # Disable links to locations
    hide: false
    map:
      # show map
      enable: true
      # initial map center point
      home_coord: 49.8951, -97.1384
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Hydda.Full
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 10

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 60 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
