title: NLP Reading Group, Dhaka
description: >-
  A Dhaka based Reading Group for Natural Language Processing and Deep Learning Research
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nlp-reading-group-dhaka.github.io/" # the base hostname & protocol for your site, e.g. https://example.com

theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/
  pages:
    output: true 
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room
  - scope:
      path: ""
      type: pages 
    values:
      layout: page 



conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: NLPDhaka
      img: logo_nlp_dhaka.png
      url:
    links:
      - name: Seminar
        relative_url: /seminar/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: FAQ
        relative_url: /faq/
      # - name: Previous Editions
      #   menu:
      #     - name: 2022 (current)
      #       disabled: true
      #     - name: 2021
      #       relative_url: /rooms/fall-2021/

  # Main landing page
  main:
    logo:
      # img: 
    links:
      - name: Seminar
        relative_url: /seminar/
      - name: Talks
        relative_url: /talks/
      - name: Registration
        absolute_url: https://forms.gle/jRtYpGA9v4LMdA6e6

  # Information boxes
  info_bars:
    # - title: Registration open for Winter 2022 reading sessions!
    #   color: primary
    #   main_only: true
    #   text: |
    #     An introductory course on deep learning and advanced Natural Language Processing (NLP) 
    #     research. We have couple of changes such as CORE TEAM and Research Jamming! Stay tuned!

    #     ---

    #     Register here - [https://forms.gle/jRtYpGA9v4LMdA6e6](https://forms.gle/jRtYpGA9v4LMdA6e6)
    - text: We usually meet each Sunday Bangladesh time 8 pm.
      color: warning
      pages_only: true
  
  # banner
  landing_banner:
    img: winter22_reading_banner.jpg
    title: winter22 banner
    main_only: true

  # Live indications
  live:
    date: 15.07.2022
    timezone: GMT-5
    time_stop: 240      # in minutes
    streaming:
      time_pause:   60  # in minutes
      time_prepend:  5  # in minutes
      time_extend:   5  # in minutes
    demo: false

  talks:
    # Talk categories
    main_categories:
      - name: Sentence Classification
        color: info
      - name: Sequence Labeling
        color: success
      - name: Seq2seq and Attention
        color: success
      - name: Pre-trained Language Models & Fine-tuning
        color: success
      - name: Question answering
        color: info
      - name: Convolutional Neural Networks 
        color: success
      - name: Deep Learning 
        color: success
      - name: Tutorial 
        color: success



    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # URL of location / room overview page
    url: '/location'

    # Disable links to locations
    hide: false 
    map:
      # show map
      enable: true
      # initial map center point
      home_coord: 49.8951, -97.1384
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Hydda.Full
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 10

  seminar:
    # URL of program page
    url: '/seminar'

    # Time steps in program table
    time_steps: 60 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true

  faq:
    # URL of faq page
    url: '/faq'